[package]
name = "mongo_rust"
version = "0.1.0"
authors = ["Clément Marescaux <cmarescaux@hotmail.com>"]
edition = "2018"

[dependencies]
mongodb = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"